### ISSUE TITLE
Uncaught TypeError: _moment2.default.range is not a function

### ISSUE THREAD

**Issue by nickbrit** [onefinestay/react-daterange-picker#66] opened 2015-09-16 19:21 UTC
I get this error after reinstall npm module.

**Comment by dphaener** [comment] 2015-09-29 16:11
:+1: Me too

**Comment by moimikey** [comment] 2015-10-20 03:24
pedestrian question... BUT.... do you have `moment` _and_ `moment-range` imported

**Comment by AlanFoster** [comment] 2015-11-07 22:48
@nickbrit Are you still facing this issue?

**Comment by rynonl** [comment] 2016-01-29 02:55
I am seeing this as of today.  Any updates?

**Comment by timaschew** [comment] 2016-02-16 20:26
Have the same issue when using module from npm.
But if I used the source from github it seems to work.
Also find out it's not suitable if you want only a single picker.
So I switched now to https://hacker0x01.github.io/react-datepicker/ it works perfect with redux-form

**Comment by szubtsovskiy** [comment] 2016-02-19 13:26
I get the similar problem in my CI environment but not when I am running the app locally. In both cases I use production build of JS bundle. It is obfuscated (thanks UglifyJS), so the message is a little bit different but after investigation it becomes obvious that I've run into the same issue.

It looks like this statement:

`require('moment-range');`

which comes after this one:

`var _moment2 = _interopRequireDefault(_moment);`

does not actually change the _moment2["default"] instance in some circumstances.

My CI environment is Codeship (Ubuntu) and this error is 100% reproduced there when I am running my integration tests. Both when app is deployed locally (OS X) and on production (a droplet on DigitalOcean with Ubuntu) there is no problem.

Apparently there is no dependency on Node or NPM. I tried different versions and got the same result.

I suspect that there is some difference in JS engines which are used in Chrome and Firefox on different operating systems. I get similar symptoms in both browsers. My conclusion is that Chrome/Firefox process JS code generated by Webpack differently under different operating systems. It explains all symptoms but does not unfortunately give a clue how to fix it. :-(

Any ideas someone? Except for switching to another plug-in?

**Comment by szubtsovskiy** [comment] 2016-02-19 17:14
I have just tested it. Apparently it depends on the operating system but not the way I thought. 

When bundle is generated under OS X it works even when the app is viewed in Chrome under Ubuntu (at least my integration test passed successfully). When bundle is generated under Ubuntu (in my setup) I get the error mentioned in the issue. 

It looks like an issue in Webpack rather than in moment-range.

**Comment by szubtsovskiy** [comment] 2016-02-22 09:11
Well, using a fresh install definitely helps. Dependency cache was my enemy, now the problem is gone completely.

**Comment by yrik** [comment] 2016-04-17 07:06
hm... have the same issue on ubuntu, on mac os it's ok.

**Comment by AlanFoster** [comment] 2016-07-20 00:18
@yrik if you are using issues, would you mind specifying what version of moment range you have in your mac and Ubuntu installs

**Comment by AlanFoster** [comment] 2016-07-20 00:21
Also ensuring that your babel loader isn't accidentally being run over third party dependencies would be a good sanity check too

**Comment by SimeonC** [comment] 2016-08-11 00:04
I just had this issue and it ended being resolved when I deleted node_modules, `npm cache clear` and `npm install`. Then there are no issues for some odd reason...

**Comment by kukuruznik** [comment] 2017-02-09 19:50
I don't use react-daterange-picker but ran into this same issue (symptoms exactly as described by @szubtsovskiy). Reinstalling the dependencies (as described above) and rebundling helped.

**Comment by Maxwin-z** [comment] 2017-05-09 02:38
When I use `yarn`, this error occurs. delete `node_modules` and `npm install` solve the problem.

**Comment by Plazmaz** [comment] 2017-10-31 22:32
Still having this issue, none of the above fixes are working for me.

**Comment by butsjoh** [comment] 2018-01-05 13:24
For anyone still landing on this. It was fixed for us if you properly extend moment with moment range (see moment range docs)

```
import Moment from 'moment'
import { extendMoment } from 'moment-range'

const moment = extendMoment(Moment);
```

**Comment by AlanFoster** [comment] 2018-05-28 00:04
This should be fixed now by the latest version, please open a new issue if this is still happening after upgrading :+1:

**Closed by AlanFoster** 2018-05-28 00:04 UTC
